# Generated by Django 4.0.3 on 2022-05-24 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_image2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image2',
            new_name='image',
        ),
    ]
