# Generated by Django 4.0.3 on 2022-04-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_rename_owner_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='banner',
            field=models.ImageField(default='default.jpg', upload_to='banner'),
        ),
    ]
