# Generated by Django 4.0.3 on 2022-05-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_post_saved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_counts',
            field=models.IntegerField(default=0),
        ),
    ]
